name: GitHub Actions github package installation test 
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # with:
        #   persist-credentials: false
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
         node-version: '16.13.2'
      - name: Install dependencies
        run: cd example-consumer && yarn --frozen-lockfile
      - run: cd example-consumer && yarn run-bundled
