name: GitHub Actions private repo package installation test 
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup git credentials
        uses: fusion-engineering/setup-git-credentials@v2
        with:
          credentials: ${{secrets.GIT_CREDENTIALS}}
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
         node-version: '16.13.2'
         registry-url: 'https://npm.pkg.github.com'
         scope: '@sschanhee'
      - name: Install dependencies
        run: cd example-consumer && yarn --frozen-lockfile
        env: 
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: cd example-consumer && yarn run-main && echo ${{ github.token }}
